# Generated by Django 2.2 on 2020-11-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='name',
        ),
    ]
